### PR TITLE
Update README.md file

### PR DESCRIPTION
**Pull request by Ibnballo1**
I Updated the name of my repo in my readme file.

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Hello @Ibnballo1  😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 
# 👏🏻 👏🏻 👏🏻 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Please create `test.md` file and then add it in the .gitignore file.
- [ ] Please add `node_modules` in .gitignore file.

[Optional]
- [ ] Please use descriptive and relevant branch name next time

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ibnballo1** [comment]
@zainsadaqat ... Thanks for the review, but I actually put the test file in the .gitignore file as requested in the project... And as for the node_modules you said I should add... It is not in the requirement.. So am confused

**Comment by Ibnballo1** [comment]
Kindly reply ASAP

**Comment by zainsadaqat** [comment]
Hi, @Ibnballo1!
Not committing node_modules implies you need to list all your modules in the package.json (and package-lock.json ) as a mandatory step. This is great because you might not have the diligence to do so, and some of the npm operations might break if you don't. 
Please read this [guide](https://flaviocopes.com/should-commit-node-modules-git/#:~:text=Not%20committing%20node_modules%20implies%20you,break%20if%20you%20don't.) if you want to know more about why we should add node_modules folder in .gitignore file.

**Review by danmainah — APPROVED** [review]
Hi @Ibnballo1, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification using @danmainah.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
